---
- name: dotfiles | ensure dotfiles are cloned
  git: repo=https://github.com/cjwfuller/dotfiles.git clone=yes dest=~/code/dotfiles.git

- name: dotfiles | link .vimrc
  file: src=~/Code/dotfiles.git/.vimrc dest=~/.vimrc state=link

- name: dotfiles | link .vim
  file: src=~/code/dotfiles.git/.vim dest=~/.vim state=link

- name: dotfiles | ensure oh-my-zsh is cloned
  git: repo=https://github.com/robbyrussell/oh-my-zsh.git clone=yes dest=~/code/oh-my-zsh.git

- name: dotfiles | link .zshrc
  file: src=~/code/dotfiles.git/.zshrc dest=~/.zshrc state=link

- name: dotfiles | link .gitconfig
  file: src=~/code/dotfiles.git/.gitconfig dest=~/.gitconfig state=link
