---
- name: brew update
  homebrew: update_homebrew=yes

- name: brew tap base_osx_main.taps
  homebrew_tap: name={{ item }} state=present
  with_items: base_osx.main.taps

- name: brew update and upgrade
  homebrew: update_homebrew=yes upgrade_all=yes

- name: brew install base_osx.main.packages
  homebrew: name={{ item }} state=upgraded
  with_items: base_osx.main.packages

- name: brew cask install base_osx.main.casks
  homebrew_cask: name={{ item }} state=installed
  with_items: base_osx.main.casks
