---
- name: Download meteor install script
  get_url:
    url=https://install.meteor.com
    dest=/tmp/meteor.sh
    mode=0440

- name: Run meteor install script
  command: /bin/sh /tmp/meteor.sh

- name: Cleanup meteor install script
  file: path=/tmp/meteor.sh state=absent

- name: Install iOS SDK for meteor
  command: meteor install-sdk ios

- name: Install Android SDK for meteor
  command: meteor install-sdk android
